<?php

use Illuminate\Database\Seeder;

class ServerInvsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $insertSQL="
        INSERT INTO `server_invs` (`id`, `created_at`, `updated_at`, `Auth_Token`, `COMSPEC`, `CONTEXT_DOCUMENT_ROOT`, `CONTEXT_PREFIX`, `DOCUMENT_ROOT`, `GATEWAY_INTERFACE`, `HTTP_ACCEPT`, `HTTP_ACCEPT_ENCODING`, `HTTP_ACCEPT_LANGUAGE`, `HTTP_CONNECTION`, `HTTP_HOST`, `HTTP_UPGRADE_INSECURE_REQUESTS`, `MIBDIRS`, `PATH`, `PHPRC`, `PHP_PEAR_SYSCONF_DIR`, `PHP_SELF`, `QUERY_STRING`, `REMOTE_ADDR`, `REMOTE_PORT`, `REQUEST_METHOD`, `REQUEST_SCHEME`, `REQUEST_TIME`, `REQUEST_TIME_FLOAT`, `REQUEST_URI`, `SCRIPT_FILENAME`, `SCRIPT_NAME`, `SERVER_ADDR`, `SERVER_ADMIN`, `SERVER_NAME`, `SERVER_PORT`, `SERVER_PROTOCOL`, `SERVER_SIGNATURE`, `SERVER_SOFTWARE`, `status`, `System_Root`, `TMP`, `WINDIR`, `HTTP_USER_AGENT`, `HTTP_REFERER`, `HTTP_CACHE_CONTROL`) VALUES
        (1, '2019-06-10 07:07:06', '2019-06-10 07:07:06', 'GGGGGG', 'FFFF', 'dsdsd', 'CCC', 'DDDasdasd', 'CGI/1.1', '', '', '', '', 'localhost', '', '', '', '', '', '', '', '', '56604', '', '', '1560109549', '1560110000', '', '', '', '', 'postmaster@localhost', 'localhost', '80', '', '', 'Apache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.30', '', '', '', '', '', '', ''),
        (2, NULL, '2019-06-10 10:32:37', 'SahadatTokenXYZ', 'C:Windowssystem32cmd.exe', 'C:/xampp/htdocs', '', 'C:/xampp/htdocs', 'CGI/1.1', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'gzip, deflate, br', 'en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7', 'keep-alive', 'localhost', '1', 'C:/xampp/php/extras/mibs', 'C:Program Files (x86)IntelIntel(R) Management Engine ComponentsiCLS;C:Program FilesIntelIntel(R) Management Engine ComponentsiCLS;C:Windowssystem32;C:Windows;C:WindowsSystem32Wbem;C:WindowsSystem32WindowsPowerShellv1.0;C:WindowsSystem32OpenSSH;C:Program F', 'xamppphp', 'xamppphp', '/multi_server/clone_server.php', '', ':', '56604', 'GET', 'http', '1560109549', '1560110000', '/multi_server/clone_server.php', 'C:/xampp/htdocs/multi_server/clone_server.php', '/multi_server/clone_server.php', '::1', 'postmaster@localhost', 'localhost', '80', 'HTTP/1.1', '\r\nApache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.30 Server at localhost Port 80\r\n', 'Apache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.30', '', 'C:Windows', 'xampp	mp', 'C:Windows', '', '', ''),
        (3, NULL, '2019-06-10 10:32:37', 'SahadatTokenXYZ', 'C:Windowssystem32cmd.exe', 'C:/xampp/htdocs', '', 'C:/xampp/htdocs', 'CGI/1.1', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'gzip, deflate, br', 'en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7', 'keep-alive', 'localhost', '1', 'C:/xampp/php/extras/mibs', 'C:Program Files (x86)IntelIntel(R) Management Engine ComponentsiCLS;C:Program FilesIntelIntel(R) Management Engine ComponentsiCLS;C:Windowssystem32;C:Windows;C:WindowsSystem32Wbem;C:WindowsSystem32WindowsPowerShellv1.0;C:WindowsSystem32OpenSSH;C:Program F', 'xamppphp', 'xamppphp', '/multi_server/clone_server.php', '', ':', '56604', 'GET', 'http', '1560109549', '1560110000', '/multi_server/clone_server.php', 'C:/xampp/htdocs/multi_server/clone_server.php', '/multi_server/clone_server.php', '::1', 'postmaster@localhost', 'localhost', '80', 'HTTP/1.1', '\r\nApache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.30 Server at localhost Port 80\r\n', 'Apache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.30', '', 'C:Windows', 'xampp	mp', 'C:Windows', '', '', ''),
        (4, NULL, '2019-06-10 10:32:37', 'SahadatTokenXYZ', 'C:Windowssystem32cmd.exe', 'C:/xampp/htdocs', '', 'C:/xampp/htdocs', 'CGI/1.1', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'gzip, deflate, br', 'en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7', 'keep-alive', 'localhost', '1', 'C:/xampp/php/extras/mibs', 'C:Program Files (x86)IntelIntel(R) Management Engine ComponentsiCLS;C:Program FilesIntelIntel(R) Management Engine ComponentsiCLS;C:Windowssystem32;C:Windows;C:WindowsSystem32Wbem;C:WindowsSystem32WindowsPowerShellv1.0;C:WindowsSystem32OpenSSH;C:Program F', 'xamppphp', 'xamppphp', '/multi_server/clone_server.php', '', ':', '56604', 'GET', 'http', '1560109549', '1560110000', '/multi_server/clone_server.php', 'C:/xampp/htdocs/multi_server/clone_server.php', '/multi_server/clone_server.php', '::1', 'postmaster@localhost', 'localhost', '80', 'HTTP/1.1', '\r\nApache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.30 Server at localhost Port 80\r\n', 'Apache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.30', '', 'C:Windows', 'xampp	mp', 'C:Windows', '', '', '');";
        DB::unprepared($insertSQL);
    }
}
